### PR TITLE
Allow language to be changed

### LINKED ISSUE #85: Language of CovidCertApp should be changeable
The language of the app is set to the phone's default and cannot be changed. This could cause problems at borders/during voyages.

Language should be changeable by user.

### PR DESCRIPTION
**Pull request by Wv5twkFEKh54vo4tta9yu7dHa3**
Closes #85

### CODE REVIEW

**Comment by Wv5twkFEKh54vo4tta9yu7dHa3** [comment]
Plumbing is there, I don't know where to put the button to change the language preference though

**Comment by Wv5twkFEKh54vo4tta9yu7dHa3** [comment]
https://user-images.githubusercontent.com/61561059/121788433-8ed52680-cbcd-11eb-87d6-9717356140ba.mp4

**Comment by Wv5twkFEKh54vo4tta9yu7dHa3** [comment]
Some code in this PR was copied from PixelDroid (GPL 3.0, don't know if compatible with MPL but it doesn't matter since I am the author and am hereby giving you a copy under the MPL)

**Comment by goebelUB** [comment]
Thanks for taking the time to work on this (and sorry that it's been so long)!
We've (re)implemented this feature in #240, the main differences being the UI and how we store the user preference.

**Pull request closed without merging**
